version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: memo-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: memo_shop
      MYSQL_USER: memo_shop_user
      MYSQL_PASSWORD: memo_shop_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - memosho p-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: memoshop-agent-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - memoshop-agent-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # RabbitMQ Message Queue
  rabbitmq:
    image: rabbitmq:3-management
    container_name: memoshop-agent-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - memoshop-agent-network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  ten:
    image: registry.cn-hangzhou.aliyuncs.com/drowning2003/ten-agent-server:1.3
    container_name: memoshop-agent-ten
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TEN_DEV_OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-3.5-turbo}
    networks:
      - memoshop-agent-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: memoshop-agent-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - memoshop-agent-network
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memoshop-agent-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # Database
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: memo_shop
      DB_USER: memo_shop_user
      DB_PASSWORD: memoshop_password
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      
      # MinIO
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: memoshop-agent-bucket
      MINIO_PUBLIC_BASE_URL: http://localhost:9000
      
      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      
      # Application
      PORT: 8080
      GIN_MODE: release
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - memoshop-agent-network

  # Frontend Service
  frontend:
    build:
      context: ./fronted
      dockerfile: Dockerfile
    container_name: memoshop-agent-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      AGENT_SERVER_URL: http://backend:8080
      TEN_DEV_SERVER_URL: http://backend:8080
      NEXT_PUBLIC_EDIT_GRAPH_MODE: "true"
    depends_on:
      - backend
    networks:
      - memoshop-agent-network

  # Agent Service
  agent:
    build:
      context: ./agent
      dockerfile: Dockerfile
    container_name: memoshop-agent-agent
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: memo_shop
      DB_USER: memo_shop_user
      DB_PASSWORD: memo_shop_password
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      
      # MinIO
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_USE_SSL: "false"
      MINIO_BUCKET: memoshop-agent-bucket
      
      # RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      
      # OpenAI API Key (需要从环境变量获取)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      
      # Application
      PYTHONPATH: /app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - memoshop-agent-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
  minio_data:
    driver: local

networks:
  memoshop-agent-network:
    driver: bridge
