# zeabur.yaml - 适配 Zeabur 的多服务部署配置

services:
  # MySQL 数据库服务
  mysql:
    image: mysql:8.0
    ports:
      - port: 3306
        type: TCP
    env:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ten_agent
      MYSQL_USER: ten_user
      MYSQL_PASSWORD: ten_password
    volumes:
      - name: mysql_data
        mount: /var/lib/mysql

  # Redis 缓存服务
  redis:
    image: redis:7-alpine
    ports:
      - port: 6379
        type: TCP
    volumes:
      - name: redis_data
        mount: /data

  # RabbitMQ 消息队列
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - port: 5672
        type: TCP
      - port: 15672
        type: HTTP
    env:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - name: rabbitmq_data
        mount: /var/lib/rabbitmq

  # MinIO 对象存储
  minio:
    image: minio/minio:latest
    ports:
      - port: 9000
        type: HTTP
      - port: 9001
        type: HTTP
    env:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - name: minio_data
        mount: /data
    start_command: "server /data --console-address :9001"

  # 后端服务 (Go/Gin)
  backend:
    source:
      type: git
      url: https://github.com/DROWNING2003/memo-shop
      directory: ./backend
    ports:
      - port: 8080
        type: HTTP
    env:
      # 数据库配置
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: "3306"
      DB_NAME: ten_agent
      DB_USER: ten_user
      DB_PASSWORD: ten_password
      
      # Redis 配置
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      
      # MinIO 配置
      MINIO_ENDPOINT: ${MINIO_HOST}:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: ten-agent-bucket
      MINIO_PUBLIC_BASE_URL: ${MINIO_PUBLIC_URL}
      
      # RabbitMQ 配置
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      
      # 应用配置
      PORT: "8080"
      GIN_MODE: release

  # 前端服务 (Next.js)
  frontend:
    source:
      type: git
      url: https://github.com/DROWNING2003/memo-shop
      directory: ./fronted
    ports:
      - port: 3000
        type: HTTP
    env:
      AGENT_SERVER_URL: ${BACKEND_URL}
      TEN_DEV_SERVER_URL: ${BACKEND_URL}
      NEXT_PUBLIC_EDIT_GRAPH_MODE: "true"

  # Agent 服务 (Python)
  agent:
    source:
      type: git
      url: https://github.com/DROWNING2003/memo-shop
      directory: ./agent
    ports:
      - port: 8000
        type: HTTP
    env:
      # 数据库配置
      DB_HOST: ${MYSQL_HOST}
      DB_PORT: "3306"
      DB_NAME: ten_agent
      DB_USER: ten_user
      DB_PASSWORD: ten_password
      
      # Redis 配置
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: "6379"
      REDIS_PASSWORD: ""
      
      # MinIO 配置
      MINIO_ENDPOINT: ${MINIO_HOST}:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_USE_SSL: "false"
      MINIO_BUCKET: ten-agent-bucket
      
      # RabbitMQ 配置
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: "5672"
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
      
      # OpenAI API Key
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      # Python 配置
      PYTHONPATH: /app

# 环境变量模板 (需要在 Zeabur 控制台中设置)
env_vars:
  # 必需的环境变量
  OPENAI_API_KEY: ""  # 需要设置你的 OpenAI API Key
  
  # 服务连接变量 (Zeabur 会自动注入)
  MYSQL_HOST: "${mysql.host}"
  REDIS_HOST: "${redis.host}"  
  RABBITMQ_HOST: "${rabbitmq.host}"
  MINIO_HOST: "${minio.host}"
  MINIO_PUBLIC_URL: "${minio.public_url}"
  BACKEND_URL: "${backend.public_url}"
